//
//  MUColor.m
//  MeetupApp
//
//  Generated by Meetup Design on 02/26/2016.
//  Copyright (c) 2016 Meetup, Inc. All rights reserved.
//

#import "MUColor.h"
@implementation MUColor

#pragma mark - Base color palette

+ (UIColor *)whiteColor {
    return [UIColor colorWithRed:1.0f green:1.0f blue:1.0f alpha:1.0f];
}

+ (UIColor *)darkGrayColor {
    return [UIColor colorWithRed:0.208f green:0.243f blue:0.282f alpha:1.0f];
}

+ (UIColor *)mediumGrayColor {
    return [UIColor colorWithRed:0.459f green:0.459f blue:0.459f alpha:1.0f];
}

+ (UIColor *)lightGrayColor {
    return [UIColor colorWithRed:0.98f green:0.98f blue:0.98f alpha:1.0f];
}

+ (UIColor *)redColor {
    return [UIColor colorWithRed:0.929f green:0.11f blue:0.251f alpha:1.0f];
}

+ (UIColor *)purpleColor {
    return [UIColor colorWithRed:0.216f green:0.118f blue:0.675f alpha:1.0f];
}

+ (UIColor *)lightPurpleColor {
    return [UIColor colorWithRed:0.122f green:0.141f blue:0.8f alpha:1.0f];
}

+ (UIColor *)yellowColor {
    return [UIColor colorWithRed:1.0f green:0.569f blue:0.102f alpha:1.0f];
}

+ (UIColor *)tealColor {
    return [UIColor colorWithRed:0.129f green:0.91f blue:0.698f alpha:1.0f];
}

+ (UIColor *)blackColor {
    return [UIColor colorWithRed:0.059f green:0.09f blue:0.129f alpha:1.0f];
}



#pragma mark - Text colors

+ (UIColor *)textPrimaryColor {
    return [UIColor colorWithRed:0.0f green:0.0f blue:0.0f alpha:0.87f];
}

+ (UIColor *)textSecondaryColor {
    return [UIColor colorWithRed:0.0f green:0.0f blue:0.0f alpha:0.54f];
}

+ (UIColor *)textTertiaryColor {
    return [UIColor colorWithRed:0.0f green:0.0f blue:0.0f alpha:0.26f];
}

+ (UIColor *)textHintColor {
    return [UIColor colorWithRed:0.0f green:0.0f blue:0.0f alpha:0.26f];
}

+ (UIColor *)textDisabledColor {
    return [UIColor colorWithRed:0.0f green:0.0f blue:0.0f alpha:0.12f];
}

+ (UIColor *)textPrimaryInvertedColor {
    return [UIColor colorWithRed:1.0f green:1.0f blue:1.0f alpha:1.0f];
}

+ (UIColor *)textSecondaryInvertedColor {
    return [UIColor colorWithRed:1.0f green:1.0f blue:1.0f alpha:0.7f];
}

+ (UIColor *)textTertiaryInvertedColor {
    return [UIColor colorWithRed:1.0f green:1.0f blue:1.0f alpha:0.3f];
}

+ (UIColor *)textHintInvertedColor {
    return [UIColor colorWithRed:1.0f green:1.0f blue:1.0f alpha:0.3f];
}

+ (UIColor *)textDisabledInvertedColor {
    return [UIColor colorWithRed:1.0f green:1.0f blue:1.0f alpha:0.12f];
}



#pragma mark - UI Colors

+ (UIColor *)accentColor {
    return [UIColor colorWithRed:0.929f green:0.11f blue:0.251f alpha:1.0f];
}

+ (UIColor *)linkColor {
    return [UIColor colorWithRed:0.929f green:0.11f blue:0.251f alpha:1.0f];
}

+ (UIColor *)buttonColor {
    return [UIColor colorWithRed:0.216f green:0.118f blue:0.675f alpha:1.0f];
}

+ (UIColor *)statusBarColor {
    return [UIColor colorWithRed:0.176f green:0.098f blue:0.545f alpha:1.0f];
}

+ (UIColor *)borderColor {
    return [UIColor colorWithRed:0.0f green:0.0f blue:0.0f alpha:0.12f];
}

+ (UIColor *)borderDarkColor {
    return [UIColor colorWithRed:0.0f green:0.0f blue:0.0f alpha:0.54f];
}

+ (UIColor *)borderInvertedColor {
    return [UIColor colorWithRed:1.0f green:1.0f blue:1.0f alpha:0.2f];
}

+ (UIColor *)borderDarkInvertedColor {
    return [UIColor colorWithRed:1.0f green:1.0f blue:1.0f alpha:0.7f];
}

+ (UIColor *)separatorColor {
    return [UIColor colorWithRed:0.0f green:0.0f blue:0.0f alpha:0.26f];
}

+ (UIColor *)successColor {
    return [UIColor colorWithRed:0.129f green:0.91f blue:0.698f alpha:1.0f];
}

+ (UIColor *)attentionColor {
    return [UIColor colorWithRed:1.0f green:0.569f blue:0.102f alpha:1.0f];
}

+ (UIColor *)highlightColor {
    return [UIColor colorWithRed:0.0f green:0.0f blue:1.0f alpha:0.05f];
}

+ (UIColor *)selectionColor {
    return [UIColor colorWithRed:0.0f green:0.0f blue:0.0f alpha:0.05f];
}

+ (UIColor *)dropShadowOpaqueColor {
    return [UIColor colorWithRed:0.459f green:0.459f blue:0.459f alpha:1.0f];
}

+ (UIColor *)dimmingOverlayColor {
    return [UIColor colorWithRed:0.0f green:0.0f blue:0.0f alpha:0.4f];
}



#pragma mark - Background colors

+ (UIColor *)contentBGColor {
    return [UIColor colorWithRed:1.0f green:1.0f blue:1.0f alpha:1.0f];
}

+ (UIColor *)contentBGInvertedColor {
    return [UIColor colorWithRed:0.059f green:0.09f blue:0.129f alpha:1.0f];
}

+ (UIColor *)collectionBGColor {
    return [UIColor colorWithRed:0.98f green:0.98f blue:0.98f alpha:1.0f];
}



#pragma mark - EXTERNAL

+ (UIColor *)facebookColor {
    return [UIColor colorWithRed:0.231f green:0.349f blue:0.596f alpha:1.0f];
}

+ (UIColor *)twitterColor {
    return [UIColor colorWithRed:0.2f green:0.8f blue:1.0f alpha:1.0f];
}

+ (UIColor *)linkedinColor {
    return [UIColor colorWithRed:0.282f green:0.459f blue:0.706f alpha:1.0f];
}

+ (UIColor *)tumblrColor {
    return [UIColor colorWithRed:0.169f green:0.286f blue:0.392f alpha:1.0f];
}

+ (UIColor *)flickrColor {
    return [UIColor colorWithRed:0.996f green:0.031f blue:0.514f alpha:1.0f];
}

+ (UIColor *)foursquareColor {
    return [UIColor colorWithRed:0.047f green:0.729f blue:0.875f alpha:1.0f];
}

+ (UIColor *)googleplusColor {
    return [UIColor colorWithRed:0.776f green:0.239f blue:0.176f alpha:1.0f];
}

+ (UIColor *)instagramColor {
    return [UIColor colorWithRed:0.306f green:0.263f blue:0.235f alpha:1.0f];
}

+ (UIColor *)redditColor {
    return [UIColor colorWithRed:0.808f green:0.89f blue:0.973f alpha:1.0f];
}

+ (UIColor *)wepayColor {
    return [UIColor colorWithRed:0.282f green:0.569f blue:0.863f alpha:1.0f];
}

+ (UIColor *)yahooColor {
    return [UIColor colorWithRed:0.482f green:0.0f blue:0.6f alpha:1.0f];
}

+ (UIColor *)outlookColor {
    return [UIColor colorWithRed:0.0f green:0.447f blue:0.776f alpha:1.0f];
}



@end
