//
//  MUColor.h
//  MeetupApp
//
//  Generated by Meetup Design on 01/28/2016.
//  Copyright (c) 2016 Meetup, Inc. All rights reserved.
//

@import UIKit;
@interface MUColor : NSObject

#pragma mark - Base color palette

+ (UIColor *)whiteColor;
+ (UIColor *)darkGrayColor;
+ (UIColor *)mediumGrayColor;
+ (UIColor *)lightGrayColor;
+ (UIColor *)redColor;
+ (UIColor *)purpleColor;
+ (UIColor *)lightPurpleColor;
+ (UIColor *)yellowColor;
+ (UIColor *)tealColor;


#pragma mark - Text colors

+ (UIColor *)textPrimaryColor;
+ (UIColor *)textSecondaryColor;
+ (UIColor *)textTertiaryColor;
+ (UIColor *)textHintColor;
+ (UIColor *)textDisabledColor;
+ (UIColor *)textPrimaryInvertedColor;
+ (UIColor *)textSecondaryInvertedColor;
+ (UIColor *)textTertiaryInvertedColor;
+ (UIColor *)textHintInvertedColor;
+ (UIColor *)textDisabledInvertedColor;


#pragma mark - UI Colors

+ (UIColor *)accentColor;
+ (UIColor *)linkColor;
+ (UIColor *)buttonColor;
+ (UIColor *)statusBarColor;
+ (UIColor *)borderColor;
+ (UIColor *)borderDarkColor;
+ (UIColor *)borderInvertedColor;
+ (UIColor *)borderDarkInvertedColor;
+ (UIColor *)separatorColor;
+ (UIColor *)successColor;
+ (UIColor *)attentionColor;
+ (UIColor *)highlightColor;
+ (UIColor *)selectionColor;
+ (UIColor *)dropShadowOpaqueColor;
+ (UIColor *)dimmingOverlayColor;


#pragma mark - Background colors

+ (UIColor *)contentBGColor;
+ (UIColor *)contentBGInvertedColor;
+ (UIColor *)collectionBGColor;


#pragma mark - EXTERNAL

+ (UIColor *)facebookColor;
+ (UIColor *)twitterColor;
+ (UIColor *)linkedinColor;
+ (UIColor *)tumblrColor;
+ (UIColor *)flickrColor;
+ (UIColor *)foursquareColor;
+ (UIColor *)googleplusColor;
+ (UIColor *)instagramColor;
+ (UIColor *)redditColor;
+ (UIColor *)wepayColor;
+ (UIColor *)yahooColor;
+ (UIColor *)outlookColor;


@end
