//
//  MUColor.h
//  MeetupApp
//
//  Generated by Meetup Design on 02/12/2015.
//  Copyright (c) 2015 Meetup, Inc. All rights reserved.
//

@import UIKit;
@interface MUColor : NSObject

#pragma mark - PRIMITIVE COLORS

+ (UIColor *)redColor;
+ (UIColor *)blueColor;
+ (UIColor *)greenColor;
+ (UIColor *)primaryGrayColor;
+ (UIColor *)secondaryGrayColor;
+ (UIColor *)tertiaryGrayColor;
+ (UIColor *)lineGrayColor;
+ (UIColor *)primaryGrayInvertedColor;
+ (UIColor *)secondaryGrayInvertedColor;
+ (UIColor *)tertiaryGrayInvertedColor;
+ (UIColor *)lineGrayInvertedColor;


#pragma mark - BACKGROUNDS

+ (UIColor *)backgroundContentColor;
+ (UIColor *)backgroundCollectionColor;
+ (UIColor *)backgroundNavColor;
+ (UIColor *)backgroundContentInvertedColor;
+ (UIColor *)backgroundContentAccentColor;


#pragma mark - DEFAULT CONTEXT

+ (UIColor *)textPrimaryColor;
+ (UIColor *)textSecondaryColor;
+ (UIColor *)textTertiaryColor;
+ (UIColor *)borderColor;
+ (UIColor *)linkColor;
+ (UIColor *)accentColor;
+ (UIColor *)yesColor;
+ (UIColor *)noColor;
+ (UIColor *)waitlistColor;
+ (UIColor *)buttonPrimaryColor;
+ (UIColor *)buttonSecondaryColor;
+ (UIColor *)buttonTertiaryBorderColor;


#pragma mark - INVERTED CONTEXT

+ (UIColor *)textPrimaryInvertedColor;
+ (UIColor *)textSecondaryInvertedColor;
+ (UIColor *)textTertiaryInvertedColor;
+ (UIColor *)borderInvertedColor;
+ (UIColor *)linkInvertedColor;
+ (UIColor *)accentInvertedColor;
+ (UIColor *)yesInvertedColor;
+ (UIColor *)noInvertedColor;
+ (UIColor *)waitlistInvertedColor;
+ (UIColor *)buttonPrimaryInvertedColor;
+ (UIColor *)buttonSecondaryInvertedColor;
+ (UIColor *)buttonTertiaryBorderInvertedColor;


#pragma mark - MISC

+ (UIColor *)overlayPressedColor;
+ (UIColor *)moneyColor;


#pragma mark - EXTERNAL

+ (UIColor *)facebookColor;
+ (UIColor *)twitterColor;
+ (UIColor *)linkedinColor;
+ (UIColor *)tumblrColor;
+ (UIColor *)flickrColor;
+ (UIColor *)foursquareColor;
+ (UIColor *)googleplusColor;
+ (UIColor *)instagramColor;
+ (UIColor *)redditColor;
+ (UIColor *)wepayColor;


@end
