//
//  MUColor.h
//  MeetupApp
//
//  Generated by Meetup Design on 01/22/2015.
//  Copyright (c) 2015 Meetup, Inc. All rights reserved.
//

@import UIKit;
@interface MUColor : NSObject

#pragma mark - Base color palette

+ (UIColor *)white;
+ (UIColor *)darkGray;
+ (UIColor *)mediumGray;
+ (UIColor *)lightGray;
+ (UIColor *)red;
+ (UIColor *)green;
+ (UIColor *)blue;
+ (UIColor *)lightBlue;
+ (UIColor *)purple;
+ (UIColor *)brown;


#pragma mark - UI Colors

+ (UIColor *)accent;
+ (UIColor *)link;


#pragma mark - EXTERNAL

+ (UIColor *)facebook;
+ (UIColor *)twitter;
+ (UIColor *)linkedin;
+ (UIColor *)tumblr;
+ (UIColor *)flickr;
+ (UIColor *)foursquare;
+ (UIColor *)googleplus;
+ (UIColor *)instagram;
+ (UIColor *)reddit;
+ (UIColor *)wepay;


@end
