//
//  MUColor.m
//  MeetupApp
//
//  Generated by Meetup Design on 01/22/2015.
//  Copyright (c) 2015 Meetup, Inc. All rights reserved.
//

#import "MUColor.h"
@implementation MUColor

#pragma mark - PRIMITIVE COLORS

+ (UIColor *)red {
    return [UIColor colorWithRed:0.886f green:0.216f blue:0.235f alpha:1.0f];
}

+ (UIColor *)blue {
    return [UIColor colorWithRed:0.224f green:0.529f blue:0.796f alpha:1.0f];
}

+ (UIColor *)green {
    return [UIColor colorWithRed:0.384f green:0.675f blue:0.459f alpha:1.0f];
}

+ (UIColor *)primaryGray {
    return [UIColor colorWithRed:0.0f green:0.0f blue:0.0f alpha:0.95f];
}

+ (UIColor *)secondaryGray {
    return [UIColor colorWithRed:0.0f green:0.0f blue:0.0f alpha:0.67f];
}

+ (UIColor *)tertiaryGray {
    return [UIColor colorWithRed:0.0f green:0.0f blue:0.0f alpha:0.47f];
}

+ (UIColor *)lineGray {
    return [UIColor colorWithRed:0.0f green:0.0f blue:0.0f alpha:0.1f];
}

+ (UIColor *)primaryGrayInverted {
    return [UIColor colorWithRed:1.0f green:1.0f blue:1.0f alpha:1.0f];
}

+ (UIColor *)secondaryGrayInverted {
    return [UIColor colorWithRed:1.0f green:1.0f blue:1.0f alpha:0.67f];
}

+ (UIColor *)tertiaryGrayInverted {
    return [UIColor colorWithRed:1.0f green:1.0f blue:1.0f alpha:0.47f];
}

+ (UIColor *)lineGrayInverted {
    return [UIColor colorWithRed:1.0f green:1.0f blue:1.0f alpha:0.2f];
}



#pragma mark - BACKGROUNDS

+ (UIColor *)backgroundContent {
    return [UIColor colorWithRed:1.0f green:1.0f blue:1.0f alpha:1.0f];
}

+ (UIColor *)backgroundCollection {
    return [UIColor colorWithRed:0.906f green:0.906f blue:0.906f alpha:1.0f];
}

+ (UIColor *)backgroundNav {
    return [UIColor colorWithRed:0.969f green:0.969f blue:0.969f alpha:1.0f];
}

+ (UIColor *)backgroundContentInverted {
    return [UIColor colorWithRed:0.208f green:0.243f blue:0.278f alpha:1.0f];
}

+ (UIColor *)backgroundContentAccent {
    return [UIColor colorWithRed:0.886f green:0.216f blue:0.235f alpha:1.0f];
}



#pragma mark - DEFAULT CONTEXT

+ (UIColor *)textPrimary {
    return [UIColor colorWithRed:0.0f green:0.0f blue:0.0f alpha:0.95f];
}

+ (UIColor *)textSecondary {
    return [UIColor colorWithRed:0.0f green:0.0f blue:0.0f alpha:0.67f];
}

+ (UIColor *)textTertiary {
    return [UIColor colorWithRed:0.0f green:0.0f blue:0.0f alpha:0.47f];
}

+ (UIColor *)border {
    return [UIColor colorWithRed:0.0f green:0.0f blue:0.0f alpha:0.1f];
}

+ (UIColor *)link {
    return [UIColor colorWithRed:0.224f green:0.529f blue:0.796f alpha:1.0f];
}

+ (UIColor *)accent {
    return [UIColor colorWithRed:0.886f green:0.216f blue:0.235f alpha:1.0f];
}

+ (UIColor *)yes {
    return [UIColor colorWithRed:0.886f green:0.216f blue:0.235f alpha:1.0f];
}

+ (UIColor *)no {
    return [UIColor colorWithRed:0.0f green:0.0f blue:0.0f alpha:0.67f];
}

+ (UIColor *)waitlist {
    return [UIColor colorWithRed:0.0f green:0.0f blue:0.0f alpha:0.67f];
}

+ (UIColor *)buttonPrimary {
    return [UIColor colorWithRed:0.886f green:0.216f blue:0.235f alpha:1.0f];
}

+ (UIColor *)buttonSecondary {
    return [UIColor colorWithRed:0.0f green:0.0f blue:0.0f alpha:0.47f];
}

+ (UIColor *)buttonTertiaryBorder {
    return [UIColor colorWithRed:0.0f green:0.0f blue:0.0f alpha:0.47f];
}



#pragma mark - INVERTED CONTEXT

+ (UIColor *)textPrimaryInverted {
    return [UIColor colorWithRed:1.0f green:1.0f blue:1.0f alpha:1.0f];
}

+ (UIColor *)textSecondaryInverted {
    return [UIColor colorWithRed:1.0f green:1.0f blue:1.0f alpha:0.67f];
}

+ (UIColor *)textTertiaryInverted {
    return [UIColor colorWithRed:1.0f green:1.0f blue:1.0f alpha:0.47f];
}

+ (UIColor *)borderInverted {
    return [UIColor colorWithRed:1.0f green:1.0f blue:1.0f alpha:0.2f];
}

+ (UIColor *)linkInverted {
    return [UIColor colorWithRed:0.224f green:0.529f blue:0.796f alpha:1.0f];
}

+ (UIColor *)accentInverted {
    return [UIColor colorWithRed:0.886f green:0.216f blue:0.235f alpha:1.0f];
}

+ (UIColor *)yesInverted {
    return [UIColor colorWithRed:0.886f green:0.216f blue:0.235f alpha:1.0f];
}

+ (UIColor *)noInverted {
    return [UIColor colorWithRed:1.0f green:1.0f blue:1.0f alpha:0.67f];
}

+ (UIColor *)waitlistInverted {
    return [UIColor colorWithRed:1.0f green:1.0f blue:1.0f alpha:0.67f];
}

+ (UIColor *)buttonPrimaryInverted {
    return [UIColor colorWithRed:0.886f green:0.216f blue:0.235f alpha:1.0f];
}

+ (UIColor *)buttonSecondaryInverted {
    return [UIColor colorWithRed:1.0f green:1.0f blue:1.0f alpha:0.47f];
}

+ (UIColor *)buttonTertiaryBorder {
    return [UIColor colorWithRed:1.0f green:1.0f blue:1.0f alpha:0.47f];
}



#pragma mark - MISC

+ (UIColor *)overlayPressed {
    return [UIColor colorWithRed:0.251f green:0.773f blue:1.0f alpha:0.2f];
}

+ (UIColor *)money {
    return [UIColor colorWithRed:0.18f green:0.694f blue:0.208f alpha:1.0f];
}



#pragma mark - EXTERNAL

+ (UIColor *)facebook {
    return [UIColor colorWithRed:0.231f green:0.349f blue:0.596f alpha:1.0f];
}

+ (UIColor *)twitter {
    return [UIColor colorWithRed:0.2f green:0.8f blue:1.0f alpha:1.0f];
}

+ (UIColor *)linkedin {
    return [UIColor colorWithRed:0.282f green:0.459f blue:0.706f alpha:1.0f];
}

+ (UIColor *)tumblr {
    return [UIColor colorWithRed:0.169f green:0.286f blue:0.392f alpha:1.0f];
}

+ (UIColor *)flickr {
    return [UIColor colorWithRed:0.996f green:0.031f blue:0.514f alpha:1.0f];
}

+ (UIColor *)foursquare {
    return [UIColor colorWithRed:0.047f green:0.729f blue:0.875f alpha:1.0f];
}

+ (UIColor *)googleplus {
    return [UIColor colorWithRed:0.776f green:0.239f blue:0.176f alpha:1.0f];
}

+ (UIColor *)instagram {
    return [UIColor colorWithRed:0.306f green:0.263f blue:0.235f alpha:1.0f];
}

+ (UIColor *)reddit {
    return [UIColor colorWithRed:0.808f green:0.89f blue:0.973f alpha:1.0f];
}

+ (UIColor *)wepay {
    return [UIColor colorWithRed:0.282f green:0.569f blue:0.863f alpha:1.0f];
}



@end
