//
//  MUColor.m
//  MeetupApp
//
//  Generated by Meetup Design on 01/22/2015.
//  Copyright (c) 2015 Meetup, Inc. All rights reserved.
//

#import "MUColor.h"
@implementation MUColor

#pragma mark - Base color palette

+ (UIColor *)white {
    return [UIColor colorWithRed:1.0f green:1.0f blue:1.0f alpha:1.0f];
}

+ (UIColor *)darkGray {
    return [UIColor colorWithRed:0.208f green:0.243f blue:0.282f alpha:1.0f];
}

+ (UIColor *)mediumGray {
    return [UIColor colorWithRed:0.902f green:0.914f blue:0.925f alpha:1.0f];
}

+ (UIColor *)lightGray {
    return [UIColor colorWithRed:0.953f green:0.965f blue:0.976f alpha:1.0f];
}

+ (UIColor *)red {
    return [UIColor colorWithRed:0.835f green:0.341f blue:0.255f alpha:1.0f];
}

+ (UIColor *)green {
    return [UIColor colorWithRed:0.549f green:0.749f blue:0.416f alpha:1.0f];
}

+ (UIColor *)blue {
    return [UIColor colorWithRed:0.224f green:0.529f blue:0.796f alpha:1.0f];
}

+ (UIColor *)lightBlue {
    return [UIColor colorWithRed:0.408f green:0.647f blue:0.851f alpha:1.0f];
}

+ (UIColor *)purple {
    return [UIColor colorWithRed:0.443f green:0.376f blue:0.667f alpha:1.0f];
}

+ (UIColor *)brown {
    return [UIColor colorWithRed:0.443f green:0.247f blue:0.098f alpha:1.0f];
}



#pragma mark - UI Colors

+ (UIColor *)accent {
    return [UIColor colorWithRed:0.835f green:0.341f blue:0.255f alpha:1.0f];
}

+ (UIColor *)link {
    return [UIColor colorWithRed:0.224f green:0.529f blue:0.796f alpha:1.0f];
}



#pragma mark - EXTERNAL

+ (UIColor *)facebook {
    return [UIColor colorWithRed:0.231f green:0.349f blue:0.596f alpha:1.0f];
}

+ (UIColor *)twitter {
    return [UIColor colorWithRed:0.2f green:0.8f blue:1.0f alpha:1.0f];
}

+ (UIColor *)linkedin {
    return [UIColor colorWithRed:0.282f green:0.459f blue:0.706f alpha:1.0f];
}

+ (UIColor *)tumblr {
    return [UIColor colorWithRed:0.169f green:0.286f blue:0.392f alpha:1.0f];
}

+ (UIColor *)flickr {
    return [UIColor colorWithRed:0.996f green:0.031f blue:0.514f alpha:1.0f];
}

+ (UIColor *)foursquare {
    return [UIColor colorWithRed:0.047f green:0.729f blue:0.875f alpha:1.0f];
}

+ (UIColor *)googleplus {
    return [UIColor colorWithRed:0.776f green:0.239f blue:0.176f alpha:1.0f];
}

+ (UIColor *)instagram {
    return [UIColor colorWithRed:0.306f green:0.263f blue:0.235f alpha:1.0f];
}

+ (UIColor *)reddit {
    return [UIColor colorWithRed:0.808f green:0.89f blue:0.973f alpha:1.0f];
}

+ (UIColor *)wepay {
    return [UIColor colorWithRed:0.282f green:0.569f blue:0.863f alpha:1.0f];
}



@end
